### PR TITLE
Feature/make edce more library friendly

### PR DESCRIPTION
**Pull request by BeTeK**
Hello

I made some changes that enabled me to use edce as library. Basically I needed that configuration file is got from custom location and I can do custom interaction instead of console.

Hope these changes will help :)

br,
Pasi

### CODE REVIEW

**Comment by Andargor** [comment]
Thanks! I'm waiting for word from FD to see how we will be going forward, I'll keep this open.

**Comment by Andargor** [comment]
I pulled the request into a branch to test, and it breaks on existing .ini files. It should gracefully fall back to defaults. I will get back to it when I have a bit more time to track down what the problem is.

**Comment by BeTeK** [comment]
Now it can handle old style config files also

**Comment by Andargor** [comment]
I'll merge since it no longer seems to affect the default workflow. However may I suggest that you put a commented out example in player_dump.py showing how this may be used to set different paths.

**Pull request merged**
