### PR TITLE
Master

### PR DESCRIPTION
**Pull request by syberphunk**
xample error:

Traceback (most recent call last):
File "./player_dump.py", line 45, in 
starsystem = data.ships[ship].starsystem
TypeError: list indices must be integers or slices, not edict

Changed to:
starsystem = data.ships[data.ships.index(ship)].starsystem

This returns the indices correctly where the ship exists in the
dictionary.

Replaced as appropriate in code with condition to handle if Python3 version is less than 3.5.

Tested against Python 3.5

### CODE REVIEW

**Comment by syberphunk** [comment]
Was also forced to clean up tabbing.

**Comment by Andargor** [comment]
I've instead opted to simply use key-value pairs instead of edict iteration to make it more elegant. Can you check if this works for your version? Fixed spaces too, did I mention I hate python for this?

I will close if it is OK, otherwise will try to find something a bit cleaner.

**Comment by syberphunk** [comment]
I had to revert my changes, to be able to merge in what you'd done, so that I could test it. It's introduced a new error:

========== All ships: ==========
Traceback (most recent call last):
  File "./player_dump.py", line 44, in <module>
    for ship, shipEntry in data.ships.items():
AttributeError: 'list' object has no attribute 'items'

I think the changes between Python3 versions are sufficient with dictionaries to make this awkward, or the code needs to be changed so that it works from 3.4 upward.

**Comment by Andargor** [comment]
Ok, I'll set up a VM with 3.5 and make sure it works with that.

**Comment by Andargor** [comment]
I've installed 3.5.2 and I'm unable to replicate the last error you have. How many ships do you own?

andargor@vm:~/dev/edce-client$ python3.5 edce_client.py

CMDR:   Andargor
System: Shinrarta Dezhra/Jameson Memorial
Ship:   Federation_Corvette
Attempting to post market data to EDDN, this may take a minute...
Done.
andargor@vm:~/dev/edce-client$ python3.5 --version
Python 3.5.2

**Comment by syberphunk** [comment]
1 ship

**Pull request closed without merging**
